version: '3.5'

services: 
  symfony-webserver:
    container_name: symfony-webserver
    build: 
      context: ./docker/nginx
      args: 
        UID: $U_ID
    ports: 
      - 300:80
    volumes: 
      - ./public:/appdata/www/public
    networks: 
      - symfony-network
    depends_on: 
      - symfony-php

  symfony-php:
    container_name: symfony-php
    build: 
      context: ./docker/php
      args: 
        UID: $U_ID
    environment: 
      PHP_IDE_CONFIG: serverName=Docker
      XDEBUG_CONFIG: remote_host=172.17.0.1 remote_port=9005
    volumes: 
      - ./:/appdata/www
      - ./docker/php/xdebug-linux.ini:/usr/local/etc/php/conf.d/xdebug.ini
    networks: 
      - symfony-network
    depends_on: 
      - symfony-db

  symfony-db:
    container_name: symfony-db
    image: mysql:8.0
    ports: 
      - 40000:3306
    environment: 
      MYSQL_DATABASE: symfony-api-database 
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: root
    command: mysqld --sql_mode="STRICT_ALL_TABLES,NO_ENGINE_SUBSTITUTION"
    volumes: 
      - symfony-api-data:/var/lib/mysql
    networks: 
      - symfony-network

volumes: 
  symfony-api-data:

networks: 
  symfony-network:
    external: true
