App\Entity\Merchants:
  attributes:
    id:
      groups: ["merchants"]
    merchant_name:
      groups: ["merchants"]
    created_at:
      groups: ["merchants"]
    country:
      groups: ["merchants"]
